[WIP] Rich notifications
microsoftgraph/msgraph-sdk-dotnet-core pull request #269
Opened 2021-06-28 11:37 UTC by andrueastman

This PR supercedes #117 and closes #268.

It involves cleanup of work done in #117

### ToDo
- [ ] test locally in webhook project
- [ ] implement unit tests

2021-07-01 23:53 UTC, MIchaelMainer approved these changes
Approved with suggestions. Vincent should review this too.

Suggestions:

1) You can remove indent levels and remove unneeded curly braces around using statements. https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#using-declarations

2) Method calls into System.Security.Cryptography can result in exceptions. I suggest that you expose that possibility in an exception doc tag. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments#exception. This way IDEs can show this developers and they can choose whether they want to handle these.

3) Long param code comment length. IDEs will make very long lines for these scenarios. Consider breaking the really long lines into two lines.

2021-07-02 07:37 UTC, andrueastman commented on src/Microsoft.Graph.Core/Extensions/IDecryptableContentExtensions.cs
> +            catch (Exception ex)
Thanks for the feedback. These should be resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/269/commits/994df340207399a39c12375fbbbd7a177b0676ca

2021-07-02 19:33 UTC, MIchaelMainer submitted a review, later dismissed

2021-07-05 13:48 UTC, baywet requested changes
thanks for picking this up! A few minor comments and I think we'll be good to merge it.

2021-07-05 13:48 UTC, baywet commented on src/Microsoft.Graph.Core/Extensions/IDecryptableContentExtensions.cs
> +        {
defensive programing

2021-07-05 13:48 UTC, baywet commented on src/Microsoft.Graph.Core/Extensions/IDecryptableContentExtensions.cs
> +            using var certificate = await certificateProvider(encryptedContent.EncryptionCertificateId, encryptedContent.EncryptionCertificateThumbprint);
defensive programing

2021-07-05 13:48 UTC, baywet commented on src/Microsoft.Graph.Core/Extensions/IEncryptableSubscriptionExtensions.cs
> +            subscription.EncryptionCertificate = Convert.ToBase64String(certificate.Export(X509ContentType.Cert));
defensive programing

2021-07-05 15:30 UTC, andrueastman commented on src/Microsoft.Graph.Core/Extensions/IDecryptableContentExtensions.cs
> +        {
Resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/269/commits/467c33678becdfa1093a184a37abc46251c7966e

2021-07-05 15:30 UTC, andrueastman commented on src/Microsoft.Graph.Core/Extensions/IEncryptableSubscriptionExtensions.cs
> +            subscription.EncryptionCertificate = Convert.ToBase64String(certificate.Export(X509ContentType.Cert));
Resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/269/commits/467c33678becdfa1093a184a37abc46251c7966e

2021-07-05 15:30 UTC, andrueastman commented on src/Microsoft.Graph.Core/Extensions/IDecryptableContentExtensions.cs
> +            using var certificate = await certificateProvider(encryptedContent.EncryptionCertificateId, encryptedContent.EncryptionCertificateThumbprint);
Resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/269/commits/467c33678becdfa1093a184a37abc46251c7966e

2021-07-05 15:32 UTC, baywet approved these changes
Thanks for taking in the changes!

2021-07-06 06:34 UTC, merged