Batch Request fixes/enhancements
microsoftgraph/msgraph-sdk-dotnet-core pull request #701
Opened 2023-08-02 13:24 UTC by andrueastman

This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/697 and closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/641

Changes include - 
- Marking `BatchResponseContent.GetNextLinkAsync()` as deprecated as nextLink property won't exist a batch response. Ref at https://github.com/microsoftgraph/microsoft-graph-docs/pull/11934
- Fixes a bug where json batching would fail if the request body were of non-json content type.
- Marks `BatchRequestContent` constructors and methods to deprecated to encourage users to use `BatchRequestContentCollection` which automatically handles more than 20 requests and has the same/consistent API surface.

2023-08-02 13:44 UTC, baywet requested changes

2023-08-02 13:44 UTC, baywet commented on src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs
> +                if (batchRequestStep.Request.Content?.Headers?.ContentType?.MediaType?.ToLowerInvariant().Contains(CoreConstants.MimeTypeNames.Application.Json)?? true)
```suggestion
                if (batchRequestStep.Request.Content?.Headers?.ContentType?.MediaType?.Contains(CoreConstants.MimeTypeNames.Application.Json, StringComparison.OrdinalIgnoreCase)?? true)
```

2023-08-03 12:01 UTC, baywet approved these changes

2023-08-08 06:50 UTC, rkodev approved these changes

2023-08-08 06:50 UTC, merged